version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: learning-center-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: cleanwave-os
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    container_name: learning-center-app
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - DATABASE_URL=db
      - DATABASE_PORT=3306
      - DATABASE_NAME=cleanwave-os
      - DATABASE_USER=root
      - DATABASE_PASSWORD=password
    depends_on:
      - db

volumes:
  mysql_data:

